### ISSUE TITLE
Lack of content of "Post-validation Actions"

### ISSUE THREAD

**Issue by kevingo** [Checkmarx/Go-SCP#23]
Hi, I found the lack of content of the [Post-Validation Actions](https://github.com/Checkmarx/Go-SCP/blob/master/src/input-validation/validation.md#post-validation-actions)

```
The Post-validation Actions used vary with the context and are divided in three separate categories:
```

**Comment by PauloASilva** [comment]
Hi @kevingo,
I was able to identify the problem and fix it ([hotfix v1.0.5][1]).

Thanks for your careful review,
Paulo A. Silva

[1]: https://github.com/Checkmarx/Go-SCP/releases/tag/v1.0.5
