### ISSUE TITLE
Suggestion: timing attacks.

### ISSUE THREAD

**Issue by FilipNikolovski** [Checkmarx/Go-SCP#24]
On https://github.com/Checkmarx/Go-SCP/blob/master/src/authentication-password-management/communicating-authentication-data.md in the code example:

```golang
record, err = db.Query("SELECT password FROM accounts WHERE username = ?", username)
if err != nil {
  // user does not exist
}

if subtle.ConstantTimeCompare([]byte(record[0]), []byte(password)) != 1 {   
  // passwords do not match
}
```

the attacker can guess if the username exists or not in the database, if you choose to return early when the user does not exist.

**Comment by PauloASilva** [comment]
Hi @FilipNikolovski,
I see your point. Do you have something in mind?

What first came to me was always force `subtle.ConstantTimeCompare` to run.

1. create a temporary variable `v` with dummy bytes (or even empty string)
2. query database
3. if there was no error AND a record was returned, assign the returned value from to the temporary variable `v`
4. compare `v` with given `password` using `subtle.ConstantTimeCompare`

* Does this satisfy your concerns?
* Would you be interested in opening a Pull Request?

Best,
Paulo A. Silva

**Comment by FilipNikolovski** [comment]
I made a PR #29 you can check it out.
