### ISSUE TITLE
suggestion: use database context methods in examples

### ISSUE THREAD

**Issue by kardianos** [Checkmarx/Go-SCP#3]
All database operations are network operations (unless you are using an embedded database like sqlite or ql). As such they should be guarded with a context using db.QueryContext(ctx, "", arg1) to prevent hanging connections.

**Comment by PauloASilva** [comment]
Hi @kardianos,
We would like to have your help on this subject.

As most of our code samples are "request agnostic", are you suggesting to replace the database/sql interface by corresponding methods which do accept `Context` (e.g. `QueryRow()` by `QueryRowContext()`)?

Can you please review [`feature/context` branch changes][1] and share whether they meet your expectations?

Regards,
Paulo

[1]: https://github.com/Checkmarx/Go-SCP/compare/develop...feature/context

**Comment by kardianos** [comment]
LGTM

**Comment by PauloASilva** [comment]
Great.

I will work on other code samples so that they follow the same approach.

Thanks
