### ISSUE TITLE
Vague code description in system configuration section

### ISSUE THREAD

**Issue by kevingo** [Checkmarx/Go-SCP#37]
In the [system configuration section](https://github.com/Checkmarx/Go-SCP/blob/master/src/system-configuration/README.md), the sample code demonstrate disable directory listing as follows: 

```go
type justFilesFilesystem struct {
    fs http.FileSystem
}

func (fs justFilesFilesystem) Open(name string) (http.File, error) {
    f, err := fs.fs.Open(name)
    if err != nil {
        return nil, err
    }
    return neuteredReaddirFile{f}, nil
}
```

However, it does not provide `neuteredReaddirFile` type here, which only show in the [files directory](https://github.com/Checkmarx/Go-SCP/blob/master/src/system-configuration/files/directoryListSafe.go).

How about describe `neuteredReaddirFile` type here that reader can easily copy&paste the sample code when reading the content here?

If you feel ok, I can open a pull request to add it to the sample code.

Thank you.

**Comment by jparnaut** [comment]
Hi @kevingo, 
Sure, seems like it would make this part clearer. 

Feel free to open a PR. 
Thank you for contributing! 
Regards.

**Comment by kevingo** [comment]
@jparnaut Thanks replying. I open a PR here: [https://github.com/Checkmarx/Go-SCP/pull/38](https://github.com/Checkmarx/Go-SCP/pull/38)

**Comment by kevingo** [comment]
merged.
