### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mrpotes** [Checkmarx/Go-SCP#39]
Hi there, 

This looks like a great book, but you seem to have selected the GPL license for it. I'm not sure I understand how the GPL (which is a software license) would apply to a book. Perhaps you might like to consider one of the Creative Commons licenses instead?

**Comment by ErezYalon** [comment]
Thanks for the question @mrpotes.
We will have a look. CC may be more fitting here.

**Comment by mrpotes** [comment]
Thanks, I guess some sort of statement about how the code snippets are licensed would also be nice to provide?

**Comment by ErezYalon** [comment]
#45 
The project moved to a Create Commons license (more specifically: [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)).
The code snippets are just part of the text of the book and can be used according to the same license.

Thanks, @mrpotes for bringing our attention to it.
