### ISSUE TITLE
Needs more information on CSRF

### ISSUE THREAD

**Issue by edsrzf** [Checkmarx/Go-SCP#41]
It feels like CSRF deserves more mention in this book. There's a brief note about it in the section on websockets and the sample HTML form in "Communicating authentication data" contains a CSRF token form field, but that's it.

There's never a definition of CSRF, let alone strategies for managing or validating CSRF tokens.

**Comment by PauloASilva** [comment]
Hi @edsrzf,
Would you like to contribute with a CSRF section?
I did assign this issue to the [v2.2 milestone][1] which should be released next August 4th.

Regards,
Paulo A. Silva

[1]: https://github.com/Checkmarx/Go-SCP/milestone/4

**Comment by PauloASilva** [comment]
Hi @edsrzf,
Would you like to review to [the new section "Cross-Site Request Forgery" added to the Go SCP][1]?

We're planning to merge and release it next Nov 3rd.

Regards,
Paulo A. Silva

[1]: https://github.com/Checkmarx/Go-SCP/blob/f8497f5676f6fa11d59695507995d1799d50e767/src/general-coding-practices/cross-site-request-forgery.md

**Comment by edsrzf** [comment]
@PauloASilva Sorry, I didn't get to it in time to review before the merge, but I have a few small suggestions. Would it be best to just make a PR?

**Comment by PauloASilva** [comment]
It would be great, please remind to open de PR to the develop branch.

Thanks a bunch,

Em 04/11/2017 03:06, "Evan Shaw" <notifications@github.com> escreveu:
