### ISSUE TITLE
Don't ignore error when password checking

### ISSUE THREAD

**Issue by edsrzf** [Checkmarx/Go-SCP#43]
In the "Communicating authentication data" section, there's this example:

```go
var ctx context.Context
var value string

ctx := context.Background()
err := db.QueryContext(ctx, "SELECT passwordHash FROM accounts WHERE username = ?", username).Scan(&value)

// we don't really care about `err` as a measure to prevent timing attacks:
// as we always do a Constant Time Compare
if subtle.ConstantTimeCompare([]byte(value), []byte(attemptPasswordHash)) != 1 {
    // passwords do not match
}
```

I think it's bad practice to ignore the error, both in terms of practicality and security.

The argument in the comment amounts to "we don't want the client to be able to tell when our database returns an error." But I'd argue that they'll be able to tell anyway, for these reasons:

* It will probably take a different amount of time for the database to return an error vs. not return an error.
* When an error is returned, `value` will be the empty string (`""`). This means:
  * The `[]byte(value)` conversion will take less time than in the no-error case.
  * `subtle.ConstantTimeCompare` will short circuit and return early because its two parameters have different length. (See [its implementation](https://golang.org/src/crypto/subtle/constant_time.go?s=501:542#L2))

Further, it doesn't matter whether the client can tell whether there's an error. If they're able to cause an error at will (for example, through SQL injection), then that's a separate security problem in itself. If they can't cause the error (for example, because the database is down), then it's independent of their input and it doesn't help them figure anything out.

**Comment by PauloASilva** [comment]
Hi @edsrzf,
I see your point and I do agree that ignoring errors is a bad practice. Even if they are not returned to the user, they should be logged for further analysis.

This section was improved in the meanwhile and I think that the original idea is now "broken".
The source code comment was meant to make clear that "the system should not disclose whether user account exists as a measure to prevent User Enumeration and/or Guessable User Account".

```Go
// ...

err := db.QueryContext(ctx, "SELECT passwordHash FROM accounts WHERE username = ?", username).Scan(&value)

if err != nil {
    log.Fatal("User does not exist!")
}

// ...
```

Thanks for pointing me out to the [subtle.ConstantTimeCompare() implementation][1] and again, you're right.

Now that you know our original goal, would you like to contribute, rewriting this part and opening a pull request?

Thanks for your careful review,
Paulo

[1]: https://golang.org/src/crypto/subtle/constant_time.go?s=501:542#L2
