### ISSUE TITLE
suggestion: incorrect handling of database connections

### ISSUE THREAD

**Issue by kardianos** [Checkmarx/Go-SCP#6]
On page:

https://github.com/Checkmarx/Go-SCP/blob/c3471ef24a7c2ca6a769457783f43c60712f087a/database-security/connections.md

`sql.Open` returns a database pool (not a connection). This *can* be closed just before the application exists, but databases will determine that the connections are closed when the OS terminates the network connections when the executable closes.

Your example code (while won't compile as is), shows db.QueryRow. QueryRow does not need to be manually closed; it will be closed after a `Scan`. Furthermore throughout I highly recommend you use the Context variants, especially with a web application. When the context is canceled, a Tx will be rolled back if not committed, a Rows (from QueryContext) will be closed, and any resources will be returned. It is important to commit/rollback a Transaction or Close a Rows either explicitly or by canceling the context. However, the example Go code does not demonstrate this.

**Comment by jparnaut** [comment]
Hi @kardianos thank you for noticing the mistake and reporting. You're right, using context does seem like a the best practice, we'll review and update the document.

We'll gladly accept a pull request if you want to submit one, otherwise it'll be corrected in the next version.

**Comment by PauloASilva** [comment]
Hi @kardianos,
I would like to have your input on this.

[The section you pointed out was rewritten][1] to

* explain the connections pool concept
* introduce Go contexts

I am not sure about the `context.Background()` as "_It is never canceled, has no values, and has no deadline._".
What would be a good context for a tiny and simple database example?
 
[1]: https://github.com/Checkmarx/Go-SCP/compare/develop...feature/database-connections

**Comment by kardianos** [comment]
I find the text explaining the nature of SQL.DB a bit confusing. How about
"sql.Open returns a *DB which is a connection pool. A connection is only
opened when needed such as when calling PingContext or QueryContext."

The context should be tied to the life of the request, so that might have a
timeout (context.WithTimeout). If this is a read query then derive the ctx
from *http.Request.Context() so if the http request is cancelled the query
will also be cancelled. You don't need to set values, though a common one
would be the user auth info set when a request comes in, then pulled off as
needed, such as for query auth or query parameters.

**Comment by PauloASilva** [comment]
Hi @kardianos,
Thanks for your time and review.

I would like to give some insight about the returned `*DB` handle as it is more than just a pool.
I will work on it to make it clearer.

I understand what you're saying about "_context should be tied to the life of the request_" but when we're not on an HTTP request but on a simple `main()` function, what context should be passed in?

As `context.Background()` isn't cancelable it does not make sense to use it.
What about something like

```go
package main

import "fmt"
import "context"
import "database/sql"
import "github.com/go-sql-driver/mysql"

func main() {
    ctx, cancel := context.WithCancel(context.Background())
    db, _ := sql.Open("mysql", "user:@/cxdb")
    defer cancel()

    var version string db.QueryRowContext(ctx, "SELECT VERSION()").Scan(&version)
    fmt.Println("Connected to:", version)
}
```

Best,
Paulo A. Silva

**Comment by kardianos** [comment]
I'm the current maintainer of `database/sql`. `*sql.DB` is just a database connection pool that is capable of opening new connections as needed (stored internal DSN from open).

For a CLI application, or long running service, I would keep one base context that is canceled when the application is canceled, possibly triggering the cancel by subscribing to os signals. You also may want to bound execution time on various queries. You may want a quick read to have a short timeout and have a batch or large operation to have a long timeout. you can manage those by creating various context with timeouts.

```go
package main

import (
    "context"
    "database/sql"
    "fmt"
    "log"
    "time"

    _ "github.com/go-sql-driver/mysql"
)

type program struct {
    base context.Context
    cancel func()
    db *sql.DB
}

func main() {
    db, err := sql.Open("mysql", "user:@/cxdb")
    if err != nil {
        log.Fatal(err)
    }
    p := &program{db: db}
    p.base, p.cancel = context.WithCancel(context.Background())

    // Wait for program termination request, cancel base context on request.
    go func() {
        osSignal := // ...
        select {
        case <-p.base.Done():
        case <-osSignal:
            p.cancel()
        }
        // Optionally wait for N milliseconds before calling os.Exit.
    }()

    err =  p.doOperation()
    if err != nil {
        log.Fatal(err)
    }
}

func (p *program) doOperation() error {
    ctx, cancel := context.WithTimeout(p.base, 10 * time.Second)
    defer cancel()

    var version string
    err := p.db.QueryRowContext(ctx, "SELECT VERSION();").Scan(&version)
    if err != nil {
        return fmt.Errorf("unable to read version %v", err)
    }
    fmt.Println("Connected to:", version)
}
```

**Comment by jparnaut** [comment]
The usage of the `context` you showed is very interesting. Using one base context to monitor the application state and other contexts for operations inside the application itself is something I hadn't thought of. 
But it does seem like the safest approach, especially in a web app as was said before.

Thank you for taking the time to help and contribute @kardianos.

**Comment by PauloASilva** [comment]
Database Security Connection section was rewritten according to you feedback: https://github.com/Checkmarx/Go-SCP/commit/dcf61220388df376607060b4c205bfde1ebbab43

Thanks to you both @kardianos @jparnaut
