### ISSUE TITLE
suggestion: avoid race conditions with Mutexes

### ISSUE THREAD

**Issue by kardianos** [Checkmarx/Go-SCP#7]
On https://github.com/Checkmarx/Go-SCP/blob/c3471ef24a7c2ca6a769457783f43c60712f087a/general-coding-practices.md

It describes a way to prevent race conditions while accessing shared resources. In Go, the proper way to avoid race conditions when accessing a shared resource is a `Mutext` found in the `sync` package.

The code you have there is code that may be used to throttle incoming connections which is completely different.

**Comment by jparnaut** [comment]
Well spotted, thank you!
Could you make a pull request with the changes you think are best? 
I'll add this issue to the next milestone.
